language: r		 
sudo: required
cache: 
  - packages
dist: trusty

warnings_are_errors: false 


r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"


r_packages: 
  - lda
  - randomForest
  - foreach
  - doParallel
  - rpart
  - pbapply

r_github_packages:
  - jimhester/covr
  - hadley/testthat
  
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2"))'

script: - |
  R CMD build --no-build-vignettes
script:
  - Rscript -e 'devtools::check("sperrorest")'

notifications:
  slack: giscience-fsu:Wkbb0S8LMk9xdfVjweh8IDZx
  on_success: change # default: always
  on_failure: change # default: always
    
after_success:
  - Rscript -e 'covr::codecov()'
