#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
dist: trusty
cache: packages
warnings_are_errors: false
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libudunits2-dev

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=0

# DO NOT CHANGE THE CODE BELOW
before_install: R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
# DO NOT CHANGE THE CODE ABOVE

matrix:
  fast_finish: true
  allow_failures:
    - env: NB='w/ lintr'
    - env: NB='w/ covr'
  include:
    - os: linux
      r: oldrel
      r_github_packages:
        - hadley/testthat
    - os: linux
      r: release
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
          provider: script
          script: R -q -e 'tic::deploy()'
          on:
            all_branches: true
      after_deploy: R -q -e 'tic::after_deploy()'
      after_script: R -q -e 'tic::after_script()'
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: release
      env: NB='w/ lintr' ## Just a label

notifications:
  slack: giscience-fsu:fIBUkXTIX9Jz70o1gIwiATYE#sperrorest
  on_success: change # default: always
  on_failure: change # default: always
  email: false
