language: r		 
sudo: required
cache: 
  - packages
dist: trusty

warnings_are_errors: false 


r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"

before_install: 
  - sudo apt-get install libnotify-bin


r_packages: 
  - lda
  - randomForest
  - foreach
  - doParallel
  - rpart
  - pbapply

r_github_packages:
  - jimhester/covr
  - hadley/testthat
  
notifications:
  slack: giscience-fsu:fIBUkXTIX9Jz70o1gIwiATYE#sperrorest
  on_success: change # default: always
  on_failure: change # default: always
  email: false
after_success:
  - Rscript -e 'covr::codecov(function_exclusions = "print\\.")'
