language: r		 
sudo: required
cache: 
  - packages
dist: trusty

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'
