language: r		 
sudo: required
cache: 
  - packages
dist: trusty

warnings_are_errors: false 


r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"


r_packages: 
  - lda
  - randomForest
  - foreach
  - doParallel
  - rpart
  - pbapply

r_github_packages:
  - jimhester/covr
  
script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check --no-build-vignettes sperrorest*tar.gz

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'
